platform :ios, '8.0'

pod 'Reachability'
pod 'AFNetworking'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'Onboard'
pod 'ViewDeck', '~> 2.2.11'
pod 'pop'
pod 'STCollapseTableView'
pod 'SVProgressHUD'
pod 'GoogleMaps'

# pod 'CSStickyHeaderFlowLayout'
# pod 'CRToast'
# pod 'MZFormSheetController'