platform :ios, '8.0'

# pod 'Onboard'
pod 'Fabric'
pod 'Crashlytics'
pod 'GoogleMaps'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'pop'
pod 'PureLayout'
pod 'AFNetworking'
pod 'Reachability'
pod 'SVProgressHUD'
pod 'APAddressBook/Swift', '0.1.14'
pod 'JSBadgeView'
pod 'ViewDeck', '2.2.11'

pod 'XLForm'

# pod 'CSStickyHeaderFlowLayout'
# pod 'CRToast'
# pod 'MZFormSheetController'
